plugins:
  - jekyll-remote-theme
  - jekyll-toc
exclude:
  - "exclude.md"   
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      toc: true
remote_theme: eecs485staff/primer-spec
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jemoji
kramdown:
  input: GFM
readme_index:
  remove_originals: true
  with_frontmatter: true