plugins:
  - jekyll-remote-theme
remote_theme: ogobrecht/hydebar
exclude:
  - "exclude.md"
toc:
    enabled: true
    h_min: 1
    h_max: 99
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
    
