plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: pages-themes/leap-day@v0.2.0
exclude:
  - "*.md"
defaults:
  -
    scope:
      path: "*.docx"
    values:
      sitemap: true
